### ISSUE TITLE
앳코더 궤짝

### ISSUE THREAD

**Issue by jwvg0425** [kajebiii/ps4u.kajebiii.com#6]
안녕하세요

앳코더 궤짝에서 문제를 점수별로 정렬해서 볼 수 있는 기능이 있었으면 좋겠습니다. 점수별로 쉬운것부터 모아서 풀고 싶어서용

까제비가 항상 잘 쓰고 있습니다!

**Comment by kajebiii** [comment]
지금 프로젝트가 너무 커져서, 아에 새로 만들 계획인데 그 때 생각해볼게욥!

**Comment by kajebiii** [comment]
![image](https://user-images.githubusercontent.com/32012515/44568880-7ba20380-a7b3-11e8-8b15-a48913d54d91.png)

일단 이런식으로 만들어볼게요

**Comment by kajebiii** [comment]
https://ps4u.kajebiii.com

**Comment by jwvg0425** [comment]
와 팬이에요!! 푼 문제 초록색으로 색칠되는 건 아직 구현이 안 된건가요? 푼 문제 초록색/ 시도했는데 실패한 건 빨간색(혹은 노란색?) 같은 배경이 들어가면 더 좋을 것 같습니다!!

**Comment by jwvg0425** [comment]
아하 로그인할 때 boj 아이디만 적고 atcoder를 비워서 안 됐네요;; 죄송합니다 ㅋㅋ atcoder 아이디 넣으니 잘 되네요.

그리고 이게 관련된 버그인 거 같은데 atcoder 아이디 비운 채로 로그인하고 atcoder 궤짝에서 좀 기다리다 새로고침하니 error 페이지가 뜨네요

**Comment by kajebiii** [comment]
아, 그런 버그가 있군요! 감사합니다.

**Comment by kajebiii** [comment]
수정했습니다.
